### ISSUE TITLE
error

### ISSUE THREAD

**Issue by geekstars** [emalyak/EMPageViewController#11]
![simulator screen shot feb 20 2017 11 24 44 pm](https://cloud.githubusercontent.com/assets/21117624/23133495/daf3a02e-f7c3-11e6-928d-20ef039fdae3.png)
help me

**Comment by PanMluvci** [comment]
dude.... wtf are u doin? I don't know what do u want help with....this comment is pointless and deserve to be locked...

**Comment by geekstars** [comment]
I use the library with such faulty file xib

**Comment by PanMluvci** [comment]
then don't use XIB if you don't know how to use them. Use Storyboard. If you can't provide more information we can't help you. See ya!

**Comment by geekstars** [comment]
my project https://github.com/geekstars/EMPageViewDemo

**Comment by geekstars** [comment]
I use the storyboard is not defective as above

**Comment by geekstars** [comment]
I'm want to use EMPageViewController with xib file

**Comment by PanMluvci** [comment]
I will try to look at your project today

**Comment by geekstars** [comment]
Thank you
I just fix it
