### ISSUE TITLE
ViewController's lifecycle methods are not forwarded to the selected view controller

### ISSUE THREAD

**Issue by ikesyo** [emalyak/EMPageViewController#19]
Since `EMPageViewController` returns `false` for `shouldAutomaticallyForwardAppearanceMethods`, the lifecycle methods called on `EMPageViewController` are not forwarded automatically to the selected view controller. The selected view controller will not get those events when pushing another VC, showing another VC modally, or backing from/closing them.

**Comment by vade** [comment]
I was just wondering about this too. Is the correct method to handle the beginbeginAppearanceTransition / endAppearanceTransition methods directly instead? Im a touch confused about best practices dealing with when to expect viewWill/Did/Appear/Dissappear to be evoked when scrolling within EMPPageViewController.

Thanks!
