### ISSUE TITLE
EMPageViewController won't support to Swift version 5.0

### ISSUE THREAD

**Issue by ajabade** [emalyak/EMPageViewController#21]
Our project is moving Swift version from 4.0 to 5.0 and this cocoapod lib won't supports for Swift 5. Could you please fix this issue?

**Comment by emalyak** [comment]
Updated the code to Swift 5.0, it's currently on the master branch. Would you be able to verify that the latest build is working correctly in your project by adding `pod 'EMPageViewController', :git => 'https://github.com/emalyak/EMPageViewController.git'` to your `Podspec` file?

If it works, I'll go ahead and publish the latest version (5.0) to CocoaPods.

Thanks!

**Comment by ajabade** [comment]
Hello Erik,

Thanks for fixed issue for Swift 5. I’ll try it and will update you.

Best Regards,
Amol

**Comment by ajabade** [comment]
Hello Erik,

Sorry for late response. I have update EMPageViewController to Swift version 5. It’s working properly.

Thank you so much for updated.

Could you please publish the latest version (5.0)?

Best Regards,
Amol

**Comment by ajabade** [comment]
Hello Erik,

When I tried to install pod, it is showing EMPageViewController (3.0.0) version, not the 5.0.0 version.
Could you please update your master branch to EMPageviewController (5.0.0) version?

**Comment by emalyak** [comment]
Published! To increase compatibility for others, I published [Version 4.0.0](https://github.com/emalyak/EMPageViewController/releases/tag/4.0.0) of EMPageViewController on CocoaPods, which adds support for Swift 4.2+.

Let me know if you run into any issues.

Thanks!

**Comment by ajabade** [comment]
Hello Erik,

Still I have been facing issue with Swift 5.

Here are code snippets.


private func addChildIfNeeded(_ viewController: UIViewController) {

        self.scrollView.addSubview(viewController.view)

        self.addChildViewController(viewController)

        viewController.didMove(toParentViewController: self)

    }



    private func removeChildIfNeeded(_ viewController: UIViewController?) {

        viewController?.view.removeFromSuperview()

        viewController?.didMove(toParentViewController: nil)

        viewController?.removeFromParentViewController()

    }

if self.isOrientationHorizontal {
            self.scrollView.contentInset = UIEdgeInsetsMake(0, beforeInset, 0, afterInset)
        } else {
            self.scrollView.contentInset = UIEdgeInsetsMake(beforeInset, 0, afterInset, 0)
        }

Also, I’ve attached screenshots for your references.

Best Regards,
Amol

**Comment by ajabade** [comment]
Hello Erik,

Still, I have been facing issues with Swift 5. 
Could you please publish pod 'EMPageViewController', :git => 'https://github.com/emalyak/EMPageViewController.git'?
