### ISSUE TITLE
Swift 3 support

### ISSUE THREAD

**Issue by sai-prasanna** [emalyak/EMPageViewController#8]
Any Ideas for swift 3 support

**Comment by emalyak** [comment]
Workin' on it ;) Expect a new release in a couple of days.

**Comment by pureblood** [comment]
Looking forward to it.

**Comment by emalyak** [comment]
Just released [version 3.0.0](https://github.com/emalyak/EMPageViewController/releases/tag/3.0.0), which includes support for Swift 3. It's also available on [Cocoapods](https://cocoapods.org/pods/EMPageViewController). Let me know if you run into any issues.

Thanks!
